apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wafer-app-ingress
  namespace: application
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.app.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.app.serviceName }}
                port:
                  number: {{ .Values.ingress.app.servicePort }}
    - host: {{ .Values.ingress.api.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.api.serviceName }}
                port:
                  number: {{ .Values.ingress.api.servicePort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wafer-ai-ingress
  namespace: ai-serving
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.ai.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.ingress.ai.serviceName }}
                port:
                  number: {{ .Values.ingress.ai.servicePort }}