apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: gitops
spec:
  project: default
  source:
    repoURL: http://gitlab.local:8929/root/kim-minji-infra.git
    targetRevision: HEAD
    path: loki
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true